name: test output

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: set_output
        run: |
          # 生成临时访问口令
          TOKEN="temporary_token_$(date +%s)"
          echo "::set-output name=token::$TOKEN"
  build2:
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: use output
        id: use_output
        run: echo "${{ needs.build.outputs.token }}"
