name: test output

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set sensitive output
        id: set_output
        run: echo "::set-output name=sensitive_output::qwer"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use sensitive output
        run: echo "${{ needs.build.outputs.sensitive_output }}"
