name: test output

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: set_output
        run: echo "::set-output name=my_output::value1"  
