name: test output

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: set_output
        run: echo "token=qwer" >> $GITHUB_ENV
      - name: use output
        id: use_output
        run: echo "${{ env.token }}"  
