# This is a basic workflow to help you get started with Actions

name: retry test

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: sleep 60 && abc
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: sleep 5 && abc
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: sleep 10 && abc 
